### ISSUE TITLE
Create plotting functions library

### ISSUE THREAD

**Issue by nusbaume** [NCAR/CAM_diagnostics#14]
Many plotting scripts use very similar functions to generate figures, which may results in lots of repeated, and potentially inefficient, code.  

To avoid this, it would help to create a CAM diagnostics plotting functions library which can (optionally) be used by all the plotting scripts to perform certain oft-repeated actions, which should hopefully reduce the overall code footprint, and allow for a single location where modifications and/or bug-fixes can be made.

**Comment by cecilehannay** [comment]
I cannot agree more on this. This would be very useful.
