### ISSUE TITLE
Need to implement the "AMWG Table"

### ISSUE THREAD

**Issue by brianpm** [NCAR/CAM_diagnostics#18]
One of the most viewed outputs of the AMWG diagnostics is the table of numbers. They just show one variable in each row of the table, with columns of the global average of the variable in the simulation, the reference simulation or observations, the difference, and the RMSE.

I'd like to propose that we could provide similar information more flexibly, and at the same time provide more information.

In the attached prototype code, I am assuming time series files (but not necessarily globally averaged already). It is configured right now as a CLI, and the function `main` orchestrates the work. It loads the file, gets the variable, checks if there are spatial dimensions (if so, do weighted average), then it does an annual average (assuming that time can be correctly parsed from the time series file), and then calculates:
- mean
- sample size
- standard deviation
- standard error of the mean
- 5%/95% confidence interval of the mean
- linear trend
- p-value of linear trend
It then puts those into a CSV file (appending if it already exists), and then it converts that CSV file into the simplest HTML file that you can imagine (example with one variable attached).

Note that this has only acted on one simulation! I haven't bothered to deal with the comparison piece. To get the RMSE will take another calculation, but I believe that will be easy to add. Having a CSV for each case might be very useful in the long run, since it would be easy to write scripts that get the stats from these files across many cases.

Adding the standard deviation, standard error, confidence interval, and linear trend analysis should provide a lot of additional value when looking at the diagnostics. Obviously if there are other things, we can add them on. 

I have done limited testing with this code, and I didn't have a chance to implement it in the current version of the package. I was hoping that @nusbaume could find a little time to do that if @cecilehannay agrees that this is a viable way to start making the table. 

[amwg_table_replacement.zip](https://github.com/NCAR/CAM_diagnostics/files/5838738/amwg_table_replacement.zip)

**Comment by cecilehannay** [comment]
The table looks fine to me. It would be good to include model to model and model to obs (including RMSE in the future). But it is a great starting point.

**Comment by nusbaume** [comment]
@brianpm Thanks for the code!  I'll try to get it implemented in the next few weeks.  If for some reason this is needed ASAP please let me know.
