### ISSUE TITLE
Need to add "cam_ts_done" variable to example YAML File

### ISSUE THREAD

**Issue by nusbaume** [NCAR/CAM_diagnostics#35]
Currently if one want to skip time series generation, but still compute the climo files, then one needs to add the variable:

`cam_ts_done: True`

To their config (YAML) file.  However, the example baseline config file does not contain this option, so for the new user its existence may not be known, and they may end up having a failed run.  Thus this option should be added to the example baseline config file, with enough written in the comments to hopefully make its use self-explanatory.

**Comment by bitterbark** [comment]
Thanks @nusbaume , that variable was just what I needed.
I'm trying to do the same for the baseline case too, although it is gate-kept by some different logic. I will keep working on it tomorrow unless you have a quick fix... If I do get it to work, can I try a pull request?

**Comment by nusbaume** [comment]
Hi @bitterbark 

Glad to hear that worked!  I think something may be wrong with your baseline setup, given the error you sent earlier via email.  There might be a quick fix, but I would need to see the YAML file itself.  If you can email it to me, or post it in a reply here, then I can quickly look it over to see if anything is wrong (beyond what the validator can do, which is basically just check for syntax errors).

Otherwise, if it turns out to be a real bug and you find a fix for it, then definitely feel free to create a PR, and we'll make sure to get the fix merged.  Thanks for offering!

**Comment by bitterbark** [comment]
Sure, it is on the cgd machines:
/home/bundy/diagnostics/CAM_diagnostics/CAM_diagnostics/config_dani_test.yaml

I was aiming for the lightest possible test--running it on existing time series files. (Which is what I did months ago, using the same files from your previous example config file). Glad to have help but I don't want to burden you with it!

BTW if you have example model data you could point me to, I could try to do it the standard way. I think we should plan to distribute something like that for users to test the system is working before they introduce the other potential source of error that will be using their own data.

**Comment by nusbaume** [comment]
Thanks for pointing me to the YAML file!  I think I found the error (if correct it is a bug on our end, whoops).

In the file `lib/CamDiag.py`, there should be a block of code starting on line 242 that looks like this:

```
         if not self.__basic_info['compare_obs']:
            try:
                if config['diag_cam_baseline_climo']['calc_cam_climo']:

                    #If so, then add CAM baseline climatology info to object:
                    self.__cam_bl_climo_info = read_config_obj(config, 'diag_cam_baseline_climo')

                    #Expand CAM baseline climo info variable strings:
                    self.__expand_references(self.__cam_climo_info, config_search_dict)
            except:
                raise KeyError("'calc_bl_cam_climo' in 'diag_cam_baseline_climo' not found in config file.  Please see 'config_example.yaml'.")
```

Can you replace that code block with just:

```
        if not self.__basic_info['compare_obs']:
            #If so, then add CAM baseline climatology info to object:
            self.__cam_bl_climo_info = read_config_obj(config, 'diag_cam_baseline_climo')

            #Expand CAM baseline climo info variable strings:
            self.__expand_references(self.__cam_climo_info, config_search_dict)
         
```

and let me know if it works?  Thanks again!

**Comment by bitterbark** [comment]
Thanks, it works. I'd like to try a pull request if that's okay. No worries if you'd rather just do it yourself.
