### ISSUE TITLE
module load python

### ISSUE THREAD

**Issue by swrneale** [NCAR/CAM_diagnostics#45]
I know it seems trivial, but I don't think ncar_pylib will run if python is not loaded - so could add module load python explcitly that into the docs somewhere. Non pythoners could fall over this I guess. Just a thought.

**Comment by nusbaume** [comment]
Thanks @swrneale!  I went ahead and added this missing step to the `README` file, so it should hopefully be obvious to a newcomer now (as it was already included in the wiki instructions too).  If you feel like it should be added somewhere else then feel free to re-open this issue.
