### ISSUE TITLE
Should config file have ability to pass configuration arguments directly to scripts?

### ISSUE THREAD

**Issue by nusbaume** [NCAR/CAM_diagnostics#6]
There are a myriad of different ways a user can configure a plotting script in python.  How should the CAM diagnostics manage the desire of a user to modify simple configuration options (e.g. the color bar used) for the diagnostic figures?  I can so far think of three options:

1.  Do not allow the user to configure the plots through the namelist.  If the user wants a plot configured differently, they can simply modify the plotting script directly, or add their own script to the namelist.  This is the simplest option from a development and maintenance standpoint, but requires users to know python in order to change anything.

2.  Allow all possible configuration options to be controlled via the namelist.  This greatly reduces the need of the user to know python in order to configure the scripts to their liking.  However, it increases the effort needed to develop and maintain the diagnostics, and may cause the namelist file itself to increase dramatically in size.

3.  Allow _some_ configuration options in the namelist, but require all other configuration options to either be determined automatically, or through option 1 (direct modification of the script itself).  This would likely be a a trade-off between options 1 and 2, both in terms of advantages and difficulties.

Any thoughts or opinions?

**Comment by brianpm** [comment]
@nusbaume --- I think I've been pondering a similar issue today, and may have a suggestion. I was actually trying to think of an appropriate way to specify an arbitrary name for the time series files, and the best thing I could think of was to allow an optional keyword argument with a glob string. To actually use that, however, I will need to alter the call to the function from CamDiag. After staring at it, I think we could make the function call super customizable with the following function:

```
import importlib

def function_caller(func_name: str, func_args: list, func_kwargs: dict = {}, module_name=None):
    """Call a function with given arguments.
    
    func_name : string, name of the function to call
    func_args : list, the arguments to pass to the function
    func_kwargs : [optional] dict, the keyword arguments to pass to the function
    module_name : [optional] string, the name of the module where func_name is defined; if not provided, assume func_name.py
    
    return : the output of func_name(*func_args, **func_kwargs)
    """
    if module_name is None:
        module_name = func_name+'.py'
    module = importlib.import_module(module_name)
    if hasattr(module, func_name) and callable(getattr(module, func_name)):
        func = getattr(module, func_name)
    return func(*func_args, **func_kwargs)
```

We'd still need to provide a mechanism for the user to specify the necessary information in the configuration file, but I think this could replace current import/exec/eval structure in CamDiag in `create_climo`, `regrid_climo`, `perform_analyses`, and `create_plots`. 

What do you think? I tested it a little and it seems to work great, but I might be missing something.

**Comment by nusbaume** [comment]
Hi @brianpm 

This is great!  I have been meaning to replace the "import/exec/eval" code (as my understanding is that those calls can do weird, un-safe things sometimes) as well as turn it into a function in order to clean-up the CamDiag object.  It looks like your fix will take care of both of those concerns and manage the argument-passing issue (at least on the back-end)!  

If you want, feel free to open a pull request with your code additions/modifications.  I can then do a quick test-run with it and merge it assuming the test-run works out okay.  Obviously the option-passing capability won't be fully implemented yet (I have some ideas for how to implement the user-facing end which we can discuss if you want), but it will at least get the package ready while also eliminating some of my lazy coding.  

Otherwise, just point me to your code base once it's all finished and I can do the Pull Request for you (it just might take me a while to get around to it).

Thanks again for these modifications, I definitely think it will improve the package!

**Comment by brianpm** [comment]
Great. I'm still trying it out. I'm having some problem with the import part; it must be something about setting the search path. I'll investigate that. Hopefully I can send you code or a PR soon.

**Comment by brianpm** [comment]
Woot! I think I've solved my implementation issues. Doing a test now. I might need help figuring out how to do a PR from my cloned repo; I'll email you if I can't figure it out.
